name: Deploy React to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Change this if using a different branch
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  # Change this if using a different branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version required for your project

      - name: Install dependencies
        run: npm install

      - name: Verify Vite installation
        run: npx vite --version

      - name: Build React app with Vite
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_SMOKE_0CAAE6A1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."   # React app location
          output_location: "dist"  # Vite's default output folder