name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Create a fresh package.json in my-app directory
      - name: Setup package.json in my-app directory
        run: |
          mkdir -p my-app
          cat > my-app/package.json << 'EOL'
          {
            "name": "project25",
            "version": "0.1.0",
            "private": true,
            "dependencies": {
              "@emotion/react": "^11.14.0",
              "@emotion/styled": "^11.14.0",
              "@mui/material": "^6.4.0",
              "bootstrap": "^5.3.3",
              "lucide-react": "^0.471.1",
              "react": "^18.2.0",
              "react-dom": "^18.2.0",
              "react-router-dom": "^6.16.0",
              "web-vitals": "^4.2.4"
            },
            "devDependencies": {
              "@vitejs/plugin-react": "^4.0.3",
              "terser": "^5.24.0",
              "vite": "^4.4.5"
            },
            "scripts": {
              "dev": "vite",
              "build": "vite build",
              "preview": "vite preview"
            }
          }
          EOL

      # Install dependencies using npm install instead of npm ci
      - name: Install dependencies
        working-directory: ./my-app
        run: npm install
        
      # Verify that terser is installed
      - name: Install terser explicitly
        working-directory: ./my-app
        run: npm install terser

      # Add react-router-dom explicitly
      - name: Install react-router-dom explicitly
        working-directory: ./my-app
        run: npm install react-router-dom

      # Create vite.config.js file
      - name: Create vite.config.js
        run: |
          cat > my-app/vite.config.js << 'EOL'
          import { defineConfig } from 'vite';
          import react from '@vitejs/plugin-react';
          import path from 'path';

          export default defineConfig({
            plugins: [react()],
            resolve: {
              alias: {
                '@': path.resolve(__dirname, './src'),
              },
            },
            build: {
              sourcemap: true,
              minify: 'terser',
              terserOptions: {
                compress: {
                  drop_console: false,
                },
              },
            },
          });
          EOL

      # Create index.html file
      - name: Create index.html
        run: |
          cat > my-app/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>Project 25</title>
            </head>
            <body>
              <div id="root"></div>
              <script type="module" src="/src/main.jsx"></script>
            </body>
          </html>
          EOL

      # Debug static web app API token name
      - name: Debug - Check token secret name
        run: |
          echo "Using AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_SMOKE_0CAAE6A1E"

      - name: Build React app with Vite
        working-directory: ./my-app
        run: npm run build

      - name: List built files
        run: |
          echo "Contents of ./my-app/dist:"
          ls -la ./my-app/dist || echo "Dist directory not found"

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_SMOKE_0CAAE6A1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "my-app"
          api_location: ""
          output_location: "dist"
          app_build_command: "npm run build"
          app_artifact_location: "dist"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_SMOKE_0CAAE6A1E }}
          action: "close"